blank_issues_enabled: true
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/6UyHPeGZAC
    about: Please ask and answer questions here.
  - name: E-mail the team
    url: "mailto:team@mintplexlabs.com"
    about: Contact the core-team about a question.