version: '3.9'

networks:
  anything-llm:
    driver: bridge

services:
  anything-llm:
    container_name: anything-llm
    image: anything-llm:latest
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    volumes:
      - "../server/documents:/app/server/documents"
      - "../server/vector-cache:/app/server/vector-cache"
      - "../server/anythingllm.db:/app/server/anythingllm.db"
      - "../collector/hotdir/:/app/collector/hotdir"
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - anything-llm